services:
  db:
    image: postgres
    command: -c config_file=/etc/postgresql.conf # use this config file instead of the default one
    volumes:
      - ./postgres/configs/custom_postgresql.conf:/etc/postgresql.conf
      - ./postgres/postgressData:/var/lib/postgresql/data
      - ./postgres/configs/seed.sql:/docker-entrypoint-initdb.d/seed.sql # scripts in this folder will be execute the first time this container is up and running
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      main_net:
        ipv4_address: 172.16.0.3

  web-db:
    build: ./postgres/.
    command: flask run --debug
    volumes:
      - ./postgres:/code
    ports:
      - "8000:5000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    networks:
      main_net:
        ipv4_address: 172.16.0.69
    depends_on:
      - db
  
  # DHCP Server
  dhcp: 
    build: ./dhcp/.
    networks:
      main_net:
        ipv4_address: 172.16.0.2

  # A dummy container for testing DHCP server
  dhcp-client:
    image: alpine:latest
    command: sh -c "apk update && apk add --no-cache net-tools dhclient && tail -f /dev/null"
    stdin_open: true
    tty: true
    cap_add:
      - "NET_ADMIN"
    networks:
      main_net:
    depends_on: 
      - dhcp

networks:
  main_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/23
          gateway: 172.16.0.1
  dmz_net:
    driver: bridge