services:
  db:
    image: postgres
    command: -c config_file=/etc/postgresql.conf # use this config file instead of the default one
    volumes:
      - ./postgres/configs/custom_postgresql.conf:/etc/postgresql.conf
      - ./postgres/postgressData:/var/lib/postgresql/data
      - ./postgres/configs/seed.sql:/docker-entrypoint-initdb.d/seed.sql # scripts in this folder will be execute the first time this container is up and running
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      main_net:
        ipv4_address: 172.16.0.3
        
  # A dummy web app to generate traffics for the db
  web-db:
    build: ./postgres/.
    command: flask run --debug
    volumes:
      - ./postgres:/code
    ports:
      - "8000:5000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    networks:
      main_net:
        ipv4_address: 172.16.0.69
    depends_on:
      - db
  
  # web server
  apache-service:
    # container_name: cmsc5063-website
    image: httpd:2.4
    ports:
      - "8080:80"      
    volumes:
      - ./webserver/public-html:/usr/local/apache2/htdocs/
      - ./webserver/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    restart: always
    cpus: 0.5 
    mem_limit: 50m
    environment:
      - APACHE_RUN_USER=www-data 
      - APACHE_RUN_GROUP=www-data 
    networks:
      public_network:
        ipv4_address: 172.16.2.2  
  
  # DHCP Server
  dhcp: 
    build: ./dhcp/.
    networks:
      main_net:
        ipv4_address: 172.16.0.2

  # A dummy container for testing DHCP server
  dhcp-client:
    image: alpine:latest
    command: sh -c "apk update && apk add --no-cache net-tools dhclient && tail -f /dev/null"
    stdin_open: true
    tty: true
    cap_add:
      - "NET_ADMIN"
    networks:
      main_net:
    depends_on: 
      - dhcp

  dns:
    image: ubuntu/bind9:latest
    volumes:
      - ./dns/db.172:/etc/bind/db.172
      - ./dns/db.nexustechnologies.com:/etc/bind/db.nexustechnologies.com
      - ./dns/named.conf.local:/etc/bind/named.conf.local
      - ./dns/named.conf.options:/etc/bind/named.conf.options
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/bind_logs:/var/log/named
    cap_add:
      - "NET_ADMIN"
    networks:
      public_network:
        ipv4_address: 172.16.2.3

  # A dummy container for testing the dns server
  dns-client:
    image: alpine:latest
    command: sh -c "apk update && apk add bind-tools && apk add c-ares && apk add curl && tail -f /dev/null"
    stdin_open: true
    tty: true
    dns:
      - 172.16.2.3
      - 8.8.8.8 # Google's DNS - For downloading stuff
    cap_add:
      - "NET_ADMIN"
    networks:
      public_network:
    depends_on: 
      - dns

networks:
  main_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/23
          gateway: 172.16.0.1
  public_network:
    driver: bridge
    #external: true #we would use this in a real life situation
    ipam:
      config:
        - subnet: 172.16.2.0/29
          gateway: 172.16.2.1
