# version: '1.0'
services:
  apache-service:
    container_name: cmsc5063-website
    image: httpd:2.4
    ports:
      - "8080:80"      
    volumes:
      - ./public-html:/usr/local/apache2/htdocs/
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    restart: always
    cpus: 0.5 
    mem_limit: 50m
    environment:
      - APACHE_RUN_USER=www-data 
      - APACHE_RUN_GROUP=www-data 
    networks:
      public_network:
        ipv4_address: 172.16.2.2         
networks:
  public_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/29
          gateway: 172.16.2.1
